import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Generated by `flutterfire configure --project mythdusk-ec0c7`.
///
/// Unsupported platforms fall back to [emulator] so `FLAVOR=dev` can still
/// boot against local emulators.
class DefaultFirebaseOptions {
  static const emulatorProjectId = 'mythdusk-emulator';

  static const googleWebClientId =
      '935090044330-ilf62gj41tcgued79dsdjltv2e4eljvn.apps.googleusercontent.com';

  static bool get hasProductionOptions =>
      android.projectId != emulatorProjectId;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return emulator;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return emulator;
    }
  }

  static const FirebaseOptions emulator = FirebaseOptions(
    apiKey: 'fake-api-key-for-emulator',
    appId: '1:0:web:emulator',
    messagingSenderId: '0',
    projectId: emulatorProjectId,
    storageBucket: 'mythdusk-emulator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqILRe5jZntZeddWToTyc-mjJLZ5L6S1c',
    appId: '1:935090044330:android:0e7bd47636946d89203fd3',
    messagingSenderId: '935090044330',
    projectId: 'mythdusk-ec0c7',
    storageBucket: 'mythdusk-ec0c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Ih-sj1ygsOELinDlHpH3wsINOlIHH7k',
    appId: '1:935090044330:ios:c57accd18c4c1a8e203fd3',
    messagingSenderId: '935090044330',
    projectId: 'mythdusk-ec0c7',
    storageBucket: 'mythdusk-ec0c7.firebasestorage.app',
    androidClientId:
        '935090044330-74gsk53bape13af0sr8kcuo9ahiq0ejq.apps.googleusercontent.com',
    iosClientId:
        '935090044330-huujhlk00tlj4tuet5bdgm73m53r5bde.apps.googleusercontent.com',
    iosBundleId: 'com.vividmemories.mythdusk',
  );
}
